--- #YAML:1.0
name:                Geo-Gpx
version:             0.16
abstract:            Create and parse GPX files.
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.31
distribution_type:   module
requires:     
    Date::Format:                  0
    Date::Parse:                   0
    HTML::Entities:                0
    Scalar::Util:                  0
    Test::More:                    0
    Time::Local:                   0
    version:                       0
    XML::Descent:                  0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Andy Armstrong <andy@hexten.net>
