# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Geo-Gpx
version:      0.14
version_from: lib/Geo/Gpx.pm
installdirs:  site
requires:
    Date::Format:                  0
    Date::Parse:                   0
    HTML::Entities:                0
    Scalar::Util:                  0
    Test::More:                    0
    Time::Local:                   0
    version:                       0
    XML::Descent:                  0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
